#!/bin/bash

TARGET="${1/%.php/}"
if test -z "$TARGET" ; then
    TARGET="AllTestsUnit"
fi

rm -Rf report
./phpunit --coverage-clover ./report/clover.xml --coverage-html ./report/html --bootstrap bootstrap.php -c phpunit.xml $1 $2 $3 $4 $5 $6 $7 $8 $9 ${TARGET//\//_}